### ISSUE TITLE
Error trying to use twitch oauth authentication

### ISSUE THREAD

**Issue by Jademalo** [streamlink/streamlink#3435]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

For years I've been using --twitch-oauth-token=<token>, but after upgrading to v2.0 this throws an unknown argument error.

### Reproduction steps / Explicit stream URLs to test

1. Add --twitch-oauth-token=<token> to arguments

### Log output

```
Failed to load plugin dplay from C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins
Traceback (most recent call last):
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 423, in load_plugins
mod = load_module(module_name, path)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\__init__.py", line 25, in load_module
spec.loader.exec_module(mod)
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\dplay.py", line 6, in <module>
from streamlink.compat import quote
ImportError: cannot import name 'quote' from 'streamlink.compat' (C:\Program Files (x86)\Streamlink\pkgs\streamlink\compat.py)
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --twitch-oauth-token=<removed>
```

### Additional comments, etc.
Has this been entirely removed in 2.0, or has the name of the argument changed? I can't test it at present, but I've used it in the past for subscriber only VODs etc.

Thanks

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Take a look at the changelog...

Twitch auth has already been removed in the `1.4.0` release:
https://github.com/streamlink/streamlink/blame/master/CHANGELOG.md#L481
(see https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851 why)

And the deprecated parameter has been removed in `2.0.0`:
https://github.com/streamlink/streamlink/blame/master/CHANGELOG.md#L20

**Comment by Jademalo** [comment]
Ah, my mistake. I even actually checked the changelog, but totally and utterly missed that. Whoops.

Thanks for the link to the reason though, much appreciated
