### ISSUE TITLE
[ustream] Python 3.7 AttributeError: 'UHSStream' object has no attribute 'url'

### ISSUE THREAD

**Issue by someoneask** [streamlink/streamlink#2518]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

I use streamlink on python 3.7 and after upgrading from version 0.14.2 to 1.1.1 get error:

Traceback (most recent call last):
  File "D:/Documents/Python projects/streamlink_test/main.py", line 3, in <module>
    url = stream['best'].url
AttributeError: 'UHSStream' object has no attribute 'url'

On Development version same error.

### Reproduction steps / Explicit stream URLs to test
Here's python code for recreating it:

```
import streamlink
stream = streamlink.streams("http://www.ustream.tv/channel/17074538")
url = stream['best'].url
print(url)
```

### Additional comments, screenshots, etc.

OS:         Windows 10
Python:     3.7.0
Streamlink: 1.1.1+30.g209e431

**Comment by skulblakka** [comment]
This seems to be a limitation of the ustream plugin. Using ```--stream-url``` results in 
```error: The stream specified cannot be translated to a URL```

**Comment by back-to** [comment]
> url = stream['best'].url

use `.to_url()` if you want a better output

```
>>> stream['best'].to_url()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "streamlink/stream/stream.py", line 44, in to_url
    raise TypeError("{0} cannot be converted to a URL".format(self.shortname()))
TypeError: uhs cannot be converted to a URL
```

---

**there is no valid ustream url, they are generated by streamlink every X seconds**
it is not possible to run it like you wanted it to.

At least for the Desktop streams which Streamlink is using now,
not sure about the Mobile streams but they were to instable, so they got replaced some time ago.

**Comment by someoneask** [comment]
But on version 0.14.2 it's work fine.
